# Configuration for MCP Server Tools
tools:
  rechercher_dans_texte_legal:
    name: rechercher_dans_texte_legal
    description: |
      Recherche un article dans un texte légal (loi, ordonnance, décret, arrêté)
      par le numéro du texte et le numéro de l'article. On peut également
      rechercher des mots clés ("mots clés" séparés par des espaces)
      dans une loi précise (n° de loi)

      Paramètres:
          - text_id: Le numéro du texte (format AAAA-NUMERO)
          - search: Mots-clés de recherche ou numéro d'article
          - champ: Champ de recherche ("ALL", "TITLE", "TABLE", 
            "NUM_ARTICLE", "ARTICLE")
          - type_recherche: Type de recherche ("TOUS_LES_MOTS_DANS_UN_CHAMP", 
            "EXPRESSION_EXACTE", "AU_MOINS_UN_MOT")
          - page_size: Nombre de résultats (max 100)

      Exemples:
          - Pour l'article 7 de la loi 78-17: 
            {text_id="78-17", search="7", champ="NUM_ARTICLE"}
          - On cherche les conditions de validité de la signature électronique : 
            {search="signature électronique validité conditions"}
    inputSchema:
      type: object
      properties:
        search:
          type: string
        text_id:
          type: string
        champ:
          type: string
          enum:
            - ALL
            - TITLE
            - TABLE
            - NUM_ARTICLE
            - ARTICLE
        type_recherche:
          type: string
          enum:
            - TOUS_LES_MOTS_DANS_UN_CHAMP
            - EXPRESSION_EXACTE
            - AU_MOINS_UN_MOT
        page_size:
          type: integer
          maximum: 100

  rechercher_code:
    name: rechercher_code
    description: |
      Recherche des articles juridiques dans les codes de loi français.

      Paramètres:
          - search: Termes de recherche (ex: "contrat de travail", 
            "légitime défense")
          - code_name: Nom du code juridique (ex: "Code civil", 
            "Code du travail")
          - champ: Champ de recherche ("ALL", "TITLE", "TABLE", 
            "NUM_ARTICLE", "ARTICLE")
          - sort: Tri des résultats ("PERTINENCE", "DATE_ASC", "DATE_DESC")
          - type_recherche: Type de recherche
          - page_size: Nombre de résultats (max 100)
          - fetch_all: Récupérer tous les résultats

      Exemples:
          - Pour le PACS dans le Code civil: 
            {search="pacte civil de solidarité", code_name="Code civil"}
    inputSchema:
      type: object
      properties:
        search:
          type: string
        code_name:
          type: string
        champ:
          type: string
        sort:
          type: string
          enum:
            - PERTINENCE
            - DATE_ASC
            - DATE_DESC
        type_recherche:
          type: string
        page_size:
          type: integer
          maximum: 100
        fetch_all:
          type: boolean
      required:
        - search
        - code_name

  rechercher_jurisprudence_judiciaire:
    name: rechercher_jurisprudence_judiciaire
    description: |
      Recherche des jurisprudences judiciaires dans la base JURI de Legifrance.

      Paramètres:
          - search: Termes ou numéros d'affaires à rechercher
          - publication_bulletin: Si publiée au bulletin ['T'] sinon ['F']
          - sort: Tri des résultats ("PERTINENCE", "DATE_DESC", "DATE_ASC")
          - champ: Champ de recherche ("ALL", "TITLE", "ABSTRATS", "TEXTE", 
            "RESUMES", "NUM_AFFAIRE")
          - type_recherche: Type de recherche
          - page_size: Nombre de résultats (max. 100)
          - fetch_all: Récupérer tous les résultats
          - juri_keys: Mots-clés pour extraire des champs comme 'titre'. 
            Par défaut, le titre, le texte et les résumés sont extraits
          - juridiction_judiciaire: Liste des juridictions à inclure parmi 
            ['Cour de cassation', 'Juridictions d'appel', ]

      Exemples :
          - Obtenir un panorama de la jurisprudence par mots clés :
              search = "tierce opposition salarié société liquidation", 
              page_size=100, juri_keys=['titre']
          - Obtenir toutes les jurisprudences sur la signature électronique :
              search = "signature électronique", fetch_all=True, 
              juri_keys=['titre', 'sommaire']
    inputSchema:
      type: object
      properties:
        search:
          type: string
        publication_bulletin:
          type: array
          items:
            type: string
            enum:
              - T
              - F
        sort:
          type: string
          enum:
            - PERTINENCE
            - DATE_DESC
            - DATE_ASC
        champ:
          type: string
        type_recherche:
          type: string
        page_size:
          type: integer
          maximum: 100
        fetch_all:
          type: boolean
        juri_keys:
          type: array
          items:
            type: string
        juridiction_judiciaire:
          type: array
          items:
            type: string
      required:
        - search

prompts:
  agent_juridique_expert:
    messages:
      - role: assistant
        content:
          - type: text
            text: |
              Tu es un agent juridique expert qui cite toujours ses sources dans le corps du texte.
              Lorsque tu effectues une recherche et que des références sont citées (article d'un code, numéro de décision de justice), 
              tu dois systématiquement utiliser les outils à ta disposition pour aller chercher leur contenu et l'analyser. 
              Tu peux utiliser tous les outils disponibles pour rechercher des informations dans les textes de loi français ou la jurisprudence.
              Tu dois :
              - Expliquer ton raisonnement étape par étape
              - Utiliser les outils pertinents
              - Fournir une synthèse claire, sourcée, avec des liens vers les articles. Tu dois impérativement récupérer les liens officiels et les citer.
      - role: user
        content:
          - type: text
            text: "Voici ma question juridique : {question}"